name: CI

on:
  push:
    branches: [ main, tests ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set Gurobi environment variables
      run: |
        echo "GUROBI_HOME=/opt/gurobi1203/linux64" >> $GITHUB_ENV
        echo "PATH=$GUROBI_HOME/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$GUROBI_HOME/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "GRB_LICENSE_FILE=$PWD/gurobi.lic" >> $GITHUB_ENV
    
    - name: Install Gurobi
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://packages.gurobi.com/12.0/gurobi12.0.3_linux64.tar.gz
        tar -xvf gurobi12.0.3_linux64.tar.gz
        rm gurobi12.0.3_linux64.tar.gz
        sudo mv gurobi1203 /opt/
    
    - name: Create Gurobi license file
      run: |
        cat <<EOF > gurobi.lic
        WLSACCESSID=${{ secrets.WLSACCESSID }}
        WLSSECRET=${{ secrets.WLSSECRET }}
        LICENSEID=${{ secrets.LICENSEID }}
        EOF

    - name: Install package and dependencies 
      run: |
        pip install --upgrade pip
        pip install gurobipy
        pip install pytest-xdist
        pip install .

    - name: Run tests
      run: |
        pytest -n auto --dist load
